kernel:
    image: linuxkit/kernel:6.6.71
    cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
    - linuxkit/init:8eea386739975a43af558eec757a7dcb3a3d2e7b
    - linuxkit/runc:667e7ea2c426a2460ca21e3da065a57dbb3369c9
    - linuxkit/containerd:a988a1a8bcbacc2c0390ca0c08f949e2b4b5915d
    - linuxkit/ca-certificates:7b32a26ca9c275d3ef32b11fe2a83dbd2aee2fdb
services:
    - name: snippetd
      image: "snippetd"
      command: ["/bin/snippetd"]
      restart: true
onboot:
    - name: boot
      image: "linuxkit/systemd:v3"
      command: ["/sbin/init"]
files:
    - path: etc/systemd/system/snippetd.service
      contents: |
        [Unit]
        Description=Snippetd Service
        After=network.target containerd.service
        Requires=containerd.service

        [Service]
        ExecStart=/bin/snippetd
        Restart=on-failure

        [Install]
        WantedBy=multi-user.target
trust:
    org:
    - linuxkit
image:
    - name: snippetd
      contents:
        - path: /bin/snippetd
          source: ./bin/snippetd
