kernel:
    image: linuxkit/kernel:6.6.71
    cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
    - linuxkit/init:8eea386739975a43af558eec757a7dcb3a3d2e7b
    - linuxkit/runc:667e7ea2c426a2460ca21e3da065a57dbb3369c9
    - linuxkit/containerd:a988a1a8bcbacc2c0390ca0c08f949e2b4b5915d
    - linuxkit/ca-certificates:7b32a26ca9c275d3ef32b11fe2a83dbd2aee2fdb
onboot:
  - name: sysctl
    image: linuxkit/sysctl:5f56434b81004b50b47ed629b222619168c2bcdf
  - name: dhcpcd
    image: linuxkit/dhcpcd:157df9ef45a035f1542ec2270e374f18efef98a5
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
    - name: snippetd
      image: alpine:3.13
      capabilities:
        - CAP_NET_RAW
        - CAP_NET_ADMIN
        - CAP_SYS_ADMIN
        - CAP_NET_BIND_SERVICE
        - CAP_CHOWN
        - CAP_SETUID
        - CAP_SETGID
        - CAP_DAC_OVERRIDE
      binds:
        - /usr/bin/snippetd:/usr/bin/snippetd
      command: ["/usr/bin/snippetd"]
files:
    - path: /usr/bin/snippetd
      source: bin/snippetd
      mode: "0755"
trust:
    org:
    - linuxkit