kernel:
    image: linuxkit/kernel:6.6.71
    cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
    - linuxkit/init:8eea386739975a43af558eec757a7dcb3a3d2e7b
    - linuxkit/runc:667e7ea2c426a2460ca21e3da065a57dbb3369c9
    - linuxkit/containerd:a988a1a8bcbacc2c0390ca0c08f949e2b4b5915d
    - linuxkit/ca-certificates:7b32a26ca9c275d3ef32b11fe2a83dbd2aee2fdb
onboot:
  - name: sysctl
    image: linuxkit/sysctl:5f56434b81004b50b47ed629b222619168c2bcdf
  - name: sysfs
    image: linuxkit/sysfs:7345172dbf4d436c861adfc27150af474194289b
  - name: modprobe
    image: linuxkit/modprobe:773ee174006ecbb412830e48889795bae40b62f9
    command: ["modprobe", "-a", "virtiofs"]
  - name: dhcpcd
    image: linuxkit/dhcpcd:157df9ef45a035f1542ec2270e374f18efef98a5
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: mount
    image: linuxkit/mount:cb8caa72248f7082fc2074ce843d53cdc15df04a
    command: ["/bin/mount", "-t", "virtiofs", "virtiofs0", "/var/lib"]
services:
    - name: getty
      image: linuxkit/getty:05eca453695984a69617f1f1f0bcdae7f7032967
      env:
        - INSECURE=true
    - name: snippetd
      image: alpine:latest
      net: host
      pid: host
      binds:
        - /etc/resolv.conf:/etc/resolv.conf
        - /run:/run
        - /tmp:/tmp
        - /etc:/hostroot/etc
        - /usr/bin/ctr:/usr/bin/ctr
        - /usr/bin/runc:/usr/bin/runc
        - /var/log:/var/log
        - /var/lib/containerd:/var/lib/containerd
        - /run/containerd/containerd.sock:/run/containerd/containerd.sock
        - /dev:/dev
        - /sys:/sys
        - /app/snippetd:/app/snippetd
      command: ["/app/snippetd"]
      capabilities:
        - all
      devices:
        - path: all
          type: a
files:
    - path: /app/snippetd
      source: ./bin/snippetd
      mode: "0755"
trust:
    org:
    - linuxkit